### ISSUE TITLE
MBB doesn't correctly ignore pins from HandyNotes: Shadowlands

### ISSUE THREAD

**Issue by KnewOne** [vallantv/MBB#13]
Using MBB and HandyNotes: Shadowlands causes MBB to recognise icons for rare mobs as buttons, loading them up in the bag and freezing the game any time i try to use map/button bag.
![image](https://user-images.githubusercontent.com/41551327/98806217-82af9d80-2421-11eb-9956-06aa25193fbf.png)
![image](https://user-images.githubusercontent.com/41551327/98806312-a8d53d80-2421-11eb-82c3-a1d464074c54.png)

Since this issue is between two addons i'll link the similar issue on the HandyNotes' addon issue page https://github.com/zarillion/handynotes-plugins/issues/29

**Comment by KnewOne** [comment]
![image](https://user-images.githubusercontent.com/41551327/98807758-cf947380-2423-11eb-9744-6d60de51e238.png)
SInce i've used the same window in that issue, i'll add this here. This is a list of frames MBB uses as icons

**Comment by zarillion** [comment]
To make MBB compatible with my plugins, it would need to ignore all `HandyNotes*Pin` frames instead of just `HandyNotesPin` frames.

**Comment by KnewOne** [comment]
Considering the info from the mod author, i've created the correspondening pull request 
https://github.com/vallantv/MBB/pull/14
Close the issue if you don't need any more info from me regarding this problem

**Comment by zarillion** [comment]
Mentioning this here as well as the above PR.

I would not go with the solution in #14. This will only ignore the pins from one of my plugins. I also have HandyNotes: Battle for Azeroth, which uses the pin names HandyNotes_BattleForAzerothPins. We have unreleased plugins for every expansion that we plan on releasing over time. That's why I mentioned the solution must ignore HandyNotes*Pins as a pattern to properly ignore them all.

**Comment by MrUzagi** [comment]
Replacing line 84 from:
`	[25] = "HandyNotesPin",`
to:
`	[25] = "HandyNotes.*Pin",`

Seems to do the trick. Pins aren't captured and there's no lag.

**Comment by BradCOnGitHub** [comment]
> 
> 
> Replacing line 84 from:
> ` [25] = "HandyNotesPin",`
> to:
> ` [25] = "HandyNotes.*Pin",`
> 
> Seems to do the trick. Pins aren't captured and there's no lag.

Confirmed

**Comment by KnewOne** [comment]
Changed the pull request to use this method instead, but resigned to using two lines both for main addon and the plugins to evade future possible problems

**Comment by bellexandria** [comment]
I can confirm, after testing #14 locally all evening, this fixed the issue :)

**Comment by vallantv** [comment]
Thanks for doing the work on this @IKnewOne and @BradCOnGitHub
