### ISSUE TITLE
Releases not published as a release asset

### ISSUE THREAD

**Issue by CosmicCleric** [vallantv/MBB#16]
Using the Ajour addon manager, and one of its features is that you can supply a URL to a github and it will pull the addon down from there.

However, it has a requirement to be able to do that, that "the addon must be published as a release asset". Apparently MBB is not published as such, so Ajour cannot see it to download it as a release.

Could you mark the releases of MBB as a "release asset" please?  Thanks in advance!

**Comment by vallantv** [comment]
I can look into this. I also need to make a new project on curseforge as the person who owns this project there didn't fix their account and it's not being published properly

**Comment by vallantv** [comment]
I've been slammed with work and haven't had time to look into this. There is a fork of MBB so it should be available directly as a curseforge package going forward. https://www.curseforge.com/wow/addons/minimapbuttonbag-reborn-mmb-reborn

**Comment by vallantv** [comment]
Got Cureforge all sorted with some excellent help from their staff. Will make a push to trigger a new package being available.
