### ISSUE TITLE
iO window is in the way

### ISSUE THREAD

**Issue by NewVenari** [vallantv/MBB#9]
I can't move the io window that tells me what my rating is, which dungeons/raid bosses i've done, etc etc after doing something in the LFG tool in game.

For example, if I have to link my cloak to a group leader, I can't, because when both the LFG tool and my character screen are open, I can't link the cloak because the stupid io "mouseover" wont go away. I can have the chat /whisper open, but i can't click on my cloak because the io screen is in the way, and if i click anywhere to try to dismiss the io window, the /whisper closes.

**Comment by NewVenari** [comment]
![Uploading 20200225_221136.jpg…]()

**Comment by vallantv** [comment]
Can you try uploading the image again?
